# Generated by Django 5.0.6 on 2024-06-21 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firsttreebusiness', models.CharField(max_length=255)),
                ('secondtreebusiness', models.CharField(max_length=255)),
            ],
        ),
    ]
